version: '3.1'

networks:
  gin-quickly-template:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mysql
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    restart: on-failure
    networks:
      - gin-quickly-template
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - gin-quickly-template
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - gin-quickly-template
