apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: hduhelp
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30637
  type: NodePort