apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-pgsql
  namespace: hduhelp
data:
  init.sql: |
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='username') THEN
        CREATE USER "username" WITH PASSWORD 'password';
    END IF;
    END
    $$;
    
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname='pgsql') THEN
        CREATE DATABASE "pgsql" ENCODING 'UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' TEMPLATE template0;
    END IF;
    END
    $$;
    
    GRANT ALL PRIVILEGES ON DATABASE "pgsql" TO "username";