apiVersion: v1
kind: Service
metadata:
  name: pgsql-service
  namespace: hduhelp
spec:
  selector:
    app: pgsql
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
  type: NodePort