apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql-pod
  namespace: hduhelp
spec:
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - name: postgres
          image: postgres:12
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: username
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: pgsql-storage
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: init-sql
          configMap:
            name: configmap-pgsql
        - name: pgsql-storage
          persistentVolumeClaim:
            claimName: pgsql-pvc